[project]
name = "scanova-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.4",
    "requests>=2.32.4",
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.32.1"
]
